export const strings = {
  app: {
    title: "مدير الحسابات المشتركة", description: "أداة لإدارة الحسابات المشتركة", loading: "جاري التحميل...",
    error: "حدث خطأ غير متوقع", retry: "إعادة المحاولة", save: "حفظ", cancel: "إلغاء", delete: "حذف",
    edit: "تعديل", create: "إنشاء", logout: "تسجيل الخروج", search: "بحث...", noData: "لا توجد بيانات لعرضها",
    actions: "الإجراءات", confirmDelete: "هل أنت متأكد من الحذف؟", confirmDeleteDesc: "لا يمكن التراجع عن هذا الإجراء.",
  },
  auth: {
    login: "تسجيل الدخول", email: "البريد الإلكتروني", password: "كلمة المرور", emailPlaceholder: "أدخل البريد الإلكتروني",
    passwordPlaceholder: "أدخل كلمة المرور", loginError: "بيانات الاعتماد غير صحيحة", loginSuccess: "تم تسجيل الدخول بنجاح",
  },
  nav: { products: "المنتجات", accounts: "الحسابات", stats: "الإحصائيات", customers: "العملاء", subscriptions: "الاشتراكات", newSale: "بيع جديد" },
  products: {
    title: "المنتجات", add: "إضافة منتج", edit: "تعديل منتج", name: "اسم المنتج", service: "الخدمة",
    defaultCapacity: "السعة الافتراضية", defaultDurationDays: "المدة الافتراضية بالأيام", defaultPrice: "السعر الافتراضي",
    notes: "ملاحظات", createSuccess: "تمت إضافة المنتج بنجاح", updateSuccess: "تم تحديث المنتج بنجاح", deleteSuccess: "تم حذف المنتج بنجاح",
  },
  accounts: {
    title: "الحسابات", add: "إضافة حساب", edit: "تعديل حساب", product: "المنتج", selectProduct: "اختر المنتج",
    label: "التسمية المميزة", email: "البريد الإلكتروني للحساب", password: "كلمة مرور الحساب", capacity: "السعة",
    status: "حالة الحساب", notes: "ملاحظات", slots: "الخانات", reveal: "إظهار", hide: "إخفاء",
    createSuccess: "تمت إضافة الحساب بنجاح", updateSuccess: "تم تحديث الحساب بنجاح", deleteSuccess: "تم حذف الحساب بنجاح",
    statusActive: "نشط", statusDisabled: "معطل", statusNeedsAttention: "يحتاج انتباه",
  },
  slots: { free: "فارغ", occupied: "مشغول", disabled: "معطل" },
  common: { required: "مطلوب", invalidEmail: "البريد الإلكتروني غير صالح", details: "التفاصيل", back: "رجوع", optional: "اختياري", currency: "د.أ", day: "يوم" },
  customers: {
    title: "العملاء", add: "إضافة عميل", edit: "تعديل العميل", name: "اسم العميل", phone: "رقم الهاتف", whatsapp: "رقم واتساب",
    email: "البريد الإلكتروني", notes: "ملاحظات", searchPlaceholder: "ابحث بالاسم أو رقم الهاتف", noResults: "لا يوجد عملاء مطابقون للبحث",
    subscriptions: "اشتراكات العميل", totalSpent: "إجمالي المدفوعات", openWhatsapp: "فتح واتساب", createSuccess: "تمت إضافة العميل بنجاح",
    updateSuccess: "تم تحديث العميل بنجاح", deleteSuccess: "تم حذف العميل بنجاح", duplicatePhone: "رقم الهاتف مستخدم لعميل آخر",
    deleteConfirm: "هل تريد حذف هذا العميل؟", deleteBlocked: "قد لا يمكن حذف عميل لديه اشتراكات", usePhoneForWhatsapp: "استخدام رقم الهاتف لواتساب",
  },
  subscriptions: {
    title: "الاشتراكات", customer: "العميل", product: "المنتج", account: "الحساب", slot: "الخانة", startDate: "تاريخ البداية",
    expiryDate: "تاريخ الانتهاء", price: "السعر", status: "الحالة", statusAll: "كل الحالات", statusActive: "نشط",
    statusExpired: "منتهي", statusCancelled: "ملغي", notes: "ملاحظات", payments: "المدفوعات", slotHistory: "سجل اشتراكات الخانة",
    cancelAction: "إلغاء الاشتراك", cancelConfirm: "هل تريد إلغاء هذا الاشتراك؟", cancelDescription: "سيتم تحرير الخانة لتصبح متاحة للبيع.",
    cancelSuccess: "تم إلغاء الاشتراك وتحرير الخانة", updateSuccess: "تم تحديث ملاحظات الاشتراك", noResults: "لا توجد اشتراكات بهذه الحالة",
  },
  sale: {
    title: "بيع جديد", intro: "أنشئ اشتراكاً وسجل الدفعة في خطوة واحدة", productStep: "1. اختر المنتج",
    productHint: "تظهر المنتجات التي لديها خانات متاحة فقط", freeSlots: "خانات متاحة", slotStep: "2. اختر الخانة",
    autoAssign: "تعيين تلقائي", autoAssignDescription: "أول خانة متاحة في أقدم حساب", manualAssign: "اختيار خانة محددة",
    selectSlot: "اختر الحساب والخانة", customerStep: "3. اختر العميل أو أنشئ عميلاً", selectedCustomer: "العميل المختار",
    newCustomer: "عميل جديد", createCustomerInline: "إنشاء العميل واختياره", datesStep: "4. التواريخ والسعر",
    paymentStep: "5. تسجيل الدفعة كاملة", paymentAmount: "مبلغ الدفعة", paymentMethod: "طريقة الدفع", paidAt: "وقت الدفع",
    methodCash: "نقدي", methodTransfer: "تحويل", methodOther: "أخرى", confirmStep: "6. تأكيد البيع", confirm: "تأكيد البيع",
    success: "تم البيع بنجاح", successDescription: "تم إنشاء الاشتراك وتسجيل الدفعة وحجز الخانة.", viewSubscription: "عرض الاشتراك",
    selectProductFirst: "اختر منتجاً لعرض الخانات المتاحة", noAvailableProducts: "لا توجد منتجات لديها خانات متاحة حالياً",
    noAvailableSlots: "لا توجد خانات متاحة لهذا المنتج", missingCustomer: "اختر عميلاً قبل تأكيد البيع",
    invalidDates: "تاريخ الانتهاء يجب أن يكون بعد تاريخ البداية", createCustomerError: "تعذر إنشاء العميل",
  },
  payments: { amount: "المبلغ", method: "الطريقة", paidAt: "تاريخ الدفع", notes: "ملاحظات" },
};
