export const strings = {
  app: {
    title: "مدير الحسابات المشتركة",
    description: "أداة لإدارة الحسابات المشتركة",
    loading: "جاري التحميل...",
    error: "حدث خطأ غير متوقع",
    retry: "إعادة المحاولة",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    create: "إنشاء",
    logout: "تسجيل الخروج",
    search: "بحث...",
    noData: "لا توجد بيانات لعرضها",
    actions: "الإجراءات",
    confirmDelete: "هل أنت متأكد من الحذف؟",
    confirmDeleteDesc: "لا يمكن التراجع عن هذا الإجراء.",
  },
  auth: {
    login: "تسجيل الدخول",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    emailPlaceholder: "أدخل البريد الإلكتروني",
    passwordPlaceholder: "أدخل كلمة المرور",
    loginError: "بيانات الاعتماد غير صحيحة",
    loginSuccess: "تم تسجيل الدخول بنجاح",
  },
  nav: {
    products: "المنتجات",
    accounts: "الحسابات",
    stats: "الإحصائيات",
  },
  products: {
    title: "المنتجات",
    add: "إضافة منتج",
    edit: "تعديل منتج",
    name: "اسم المنتج",
    service: "الخدمة (مثل نتفلكس، سبوتيفاي)",
    defaultCapacity: "السعة الافتراضية (عدد الخانات)",
    defaultDurationDays: "المدة الافتراضية (بالأيام)",
    defaultPrice: "السعر الافتراضي",
    notes: "ملاحظات",
    createSuccess: "تم إضافة المنتج بنجاح",
    updateSuccess: "تم تحديث المنتج بنجاح",
    deleteSuccess: "تم حذف المنتج بنجاح",
  },
  accounts: {
    title: "الحسابات",
    add: "إضافة حساب",
    edit: "تعديل حساب",
    product: "المنتج",
    selectProduct: "اختر المنتج",
    label: "التسمية المميزة",
    email: "البريد الإلكتروني للحساب",
    password: "كلمة مرور الحساب",
    capacity: "السعة (عدد الخانات)",
    status: "حالة الحساب",
    notes: "ملاحظات",
    slots: "الخانات",
    reveal: "إظهار",
    hide: "إخفاء",
    createSuccess: "تم إضافة الحساب بنجاح",
    updateSuccess: "تم تحديث الحساب بنجاح",
    deleteSuccess: "تم حذف الحساب بنجاح",
    statusActive: "نشط",
    statusDisabled: "معطّل",
    statusNeedsAttention: "يحتاج انتباه",
  },
  slots: {
    free: "فارغ",
    occupied: "مشغول",
    disabled: "معطّل",
  }
};
