export const strings = {
  app: {
    title: "تسهيل للحسابات", description: "أداة لإدارة الحسابات المشتركة", loading: "جاري التحميل...",
    error: "حدث خطأ غير متوقع", retry: "إعادة المحاولة", save: "حفظ", cancel: "إلغاء", delete: "حذف",
    edit: "تعديل", create: "إنشاء", logout: "تسجيل الخروج", search: "بحث...", noData: "لا توجد بيانات لعرضها",
    actions: "الإجراءات", confirmDelete: "هل أنت متأكد من الحذف؟", confirmDeleteDesc: "لا يمكن التراجع عن هذا الإجراء.",
    deleteError: "تعذر الحذف. قد يكون هذا العنصر مرتبطاً ببيانات أخرى.",
  },
  login: {
    brandName: "تسهيل للحسابات",
    brandNameLead: "تسهيل",
    brandNameTrail: "للحسابات",
    tagline: "نظّم حساباتك المشتركة وعملاءك واشتراكاتك في مكان واحد",
    intro: "منصة متكاملة لإدارة الحسابات المشتركة: تتابع الاشتراكات، تنبّهك قبل انتهائها، وتنظّم مدفوعات عملائك.",
    formLead: "سجّل الدخول للمتابعة إلى لوحة التحكم",
    registerLead: "أنشئ حسابك وابدأ بإدارة اشتراكاتك",
    featureSubscriptions: "الاشتراكات",
    featureSubscriptionsDesc: "تابع كل اشتراكات عملائك في مكان واحد",
    featureExpiry: "تنبيهات الانتهاء",
    featureExpiryDesc: "ننبّهك قبل انتهاء أي اشتراك بوقتٍ كافٍ",
    featurePayments: "المدفوعات",
    featurePaymentsDesc: "سجّل الدفعات وتابع إيراداتك بدقّة",
    socialProof: "يثق به كثير من أصحاب الأعمال",
  },
  about: {
    title: "حول التطبيق",
    poweredBy: "تم التطوير بواسطة تسهيل",
    description: "تم تطوير هذا التطبيق بواسطة تسهيل (Tasheel)، فريق يبني أدوات لتسهيل إدارة الأعمال.",
    visit: "زيارة موقع تسهيل",
    url: "https://abdullamattar.github.io/Tasheel/",
    back: "العودة",
  },
  notFound: {
    message: "الصفحة التي تبحث عنها غير موجودة.",
    goHome: "العودة إلى الرئيسية",
  },
  auth: {
    login: "تسجيل الدخول", email: "البريد الإلكتروني", password: "كلمة المرور", emailPlaceholder: "أدخل البريد الإلكتروني",
    passwordPlaceholder: "أدخل كلمة المرور", loginError: "بيانات الاعتماد غير صحيحة", loginSuccess: "تم تسجيل الدخول بنجاح",
    register: "إنشاء حساب", registerTitle: "إنشاء حساب جديد", name: "الاسم", namePlaceholder: "أدخل اسمك الكامل",
    confirmPassword: "تأكيد كلمة المرور", confirmPasswordPlaceholder: "أعد إدخال كلمة المرور",
    passwordMismatch: "كلمتا المرور غير متطابقتين", passwordTooShort: "كلمة المرور يجب أن تكون 8 أحرف على الأقل",
    registerSuccess: "تم إنشاء الحساب بنجاح", registerError: "تعذر إنشاء الحساب",
    suspendedTitle: "الحساب موقوف",
    suspendedContactLabel: "تواصل عبر واتساب",
    suspendedContactUrl: "https://wa.me/962796714521",
    switchToRegister: "ليس لديك حساب؟ أنشئ حساباً جديداً", switchToLogin: "لديك حساب؟ سجّل الدخول",
  },
  nav: { products: "المنتجات", accounts: "الحسابات", inventory: "المخزون", stats: "الإحصائيات", customers: "العملاء", subscriptions: "الاشتراكات", newSale: "بيع جديد" },
  inventory: {
    title: "المنتجات والحسابات",
    description: "كل منتج يحدد طريقة البيع، وتحته تظهر الحسابات الحقيقية والخانات المتاحة للعملاء.",
    startTitle: "ابدأ بإضافة أول منتج",
    startDescription: "أضف المنتج أولاً لتحديد السعر والمدة والسعة، ثم أضف الحسابات التابعة له.",
    defaultPrice: "السعر الافتراضي",
    defaultCapacity: "السعة الافتراضية",
    defaultDuration: "المدة الافتراضية",
    accountsCount: "عدد الحسابات",
    addAccountToProduct: "إضافة حساب",
    noAccountsTitle: "لا توجد حسابات لهذا المنتج",
    noAccountsDescription: "أضف حساباً حقيقياً لتوفير خانات يمكن بيعها للعملاء.",
    addFirstAccount: "إضافة أول حساب",
    slotUsage: "الخانات المستخدمة",
  },
  products: {
    title: "المنتجات", add: "إضافة منتج", edit: "تعديل منتج", name: "اسم المنتج", service: "الخدمة",
    defaultCapacity: "السعة الافتراضية", defaultDurationDays: "المدة الافتراضية بالأيام", defaultPrice: "السعر الافتراضي",
    notes: "ملاحظات", createSuccess: "تمت إضافة المنتج بنجاح", updateSuccess: "تم تحديث المنتج بنجاح", deleteSuccess: "تم حذف المنتج بنجاح",
  },
  accounts: {
    title: "الحسابات", add: "إضافة حساب", edit: "تعديل حساب", product: "المنتج", selectProduct: "اختر المنتج",
    label: "التسمية المميزة", email: "البريد الإلكتروني للحساب", password: "كلمة مرور الحساب", capacity: "السعة",
    status: "حالة الحساب", notes: "ملاحظات", slots: "الخانات", reveal: "إظهار", hide: "إخفاء",
    startDate: "تاريخ بداية الحساب", expiryDate: "تاريخ انتهاء الحساب",
    createSuccess: "تمت إضافة الحساب بنجاح", updateSuccess: "تم تحديث الحساب بنجاح", deleteSuccess: "تم حذف الحساب بنجاح",
    statusActive: "نشط", statusDisabled: "معطل", statusNeedsAttention: "يحتاج انتباه",
  },
  slots: { free: "فارغ", occupied: "مشغول", disabled: "معطل" },
  common: { required: "مطلوب", invalidEmail: "البريد الإلكتروني غير صالح", details: "التفاصيل", back: "رجوع", optional: "اختياري", currency: "د.أ", day: "يوم", previous: "السابق", next: "التالي", page: "صفحة" },
  customers: {
    title: "العملاء", add: "إضافة عميل", edit: "تعديل العميل", name: "اسم العميل", phone: "رقم الهاتف", whatsapp: "رقم واتساب",
    email: "البريد الإلكتروني", notes: "ملاحظات", searchPlaceholder: "ابحث بالاسم أو رقم الهاتف", noResults: "لا يوجد عملاء مطابقون للبحث",
    subscriptions: "اشتراكات العميل", totalSpent: "إجمالي المدفوعات", openWhatsapp: "فتح واتساب", createSuccess: "تمت إضافة العميل بنجاح",
    updateSuccess: "تم تحديث العميل بنجاح", deleteSuccess: "تم حذف العميل بنجاح", duplicatePhone: "رقم الهاتف مستخدم لعميل آخر",
    deleteConfirm: "هل تريد حذف هذا العميل؟", deleteBlocked: "قد لا يمكن حذف عميل لديه اشتراكات", usePhoneForWhatsapp: "استخدام رقم الهاتف لواتساب",
  },
  subscriptions: {
    title: "الاشتراكات", customer: "العميل", product: "المنتج", account: "الحساب", slot: "الخانة", startDate: "تاريخ البداية",
    expiryDate: "تاريخ الانتهاء", remainingDays: "الأيام المتبقية", price: "السعر", status: "الحالة", statusAll: "كل الحالات", statusActive: "نشط",
    statusExpired: "منتهي", statusCancelled: "ملغي", notes: "ملاحظات", payments: "المدفوعات", slotHistory: "سجل اشتراكات الخانة",
    cancelAction: "إلغاء الاشتراك", cancelConfirm: "هل تريد إلغاء هذا الاشتراك؟", cancelDescription: "سيتم تحرير الخانة لتصبح متاحة للبيع.",
    cancelSuccess: "تم إلغاء الاشتراك وتحرير الخانة", refundQuestion: "هل تم إرجاع المبلغ للعميل؟", refundDescription: "سيتم تسجيل استرداد كامل وخصمه من الإيرادات.", refund: "مبلغ مسترد", refundAction: "تسجيل إرجاع المبلغ", refundConfirm: "هل تم إرجاع المبلغ لهذا العميل؟", refundOldDescription: "سيتم خصم كامل المبلغ المتبقي من الإيرادات وتسجيله في سجل المدفوعات.", refundSuccess: "تم تسجيل إرجاع المبلغ وخصمه من الإيرادات", updateSuccess: "تم تحديث ملاحظات الاشتراك", noResults: "لا توجد اشتراكات بهذه الحالة",
  },
  sale: {
    title: "بيع جديد", intro: "أنشئ اشتراكاً وسجل الدفعة في خطوة واحدة", productStep: "1. اختر المنتج",
    productHint: "تظهر المنتجات التي لديها خانات متاحة فقط", freeSlots: "خانات متاحة", slotStep: "3. اختر الخانة",
    autoAssign: "تعيين تلقائي", autoAssignDescription: "أول خانة متاحة في أقدم حساب", manualAssign: "اختيار خانة محددة",
    selectSlot: "اختر الحساب والخانة", customerStep: "2. اختر العميل أو أنشئ عميلاً", selectedCustomer: "العميل المختار",
    newCustomer: "عميل جديد", createCustomerInline: "إنشاء العميل واختياره", datesStep: "4. السعر والدفع", accountDatesHint: "تاريخ البداية والانتهاء يؤخذان تلقائياً من الحساب المختار.",
    paymentAmount: "مبلغ الدفعة", paymentMethod: "طريقة الدفع", paidAt: "وقت الدفع",
    methodCash: "نقدي", methodTransfer: "تحويل", methodOther: "أخرى", confirmStep: "5. تأكيد البيع", confirm: "تأكيد البيع",
    success: "تم البيع بنجاح", successDescription: "تم إنشاء الاشتراك وتسجيل الدفعة وحجز الخانة.", viewSubscription: "عرض الاشتراك",
    selectProductFirst: "اختر منتجاً لعرض الخانات المتاحة", noAvailableProducts: "لا توجد منتجات لديها خانات متاحة حالياً",
    noAvailableSlots: "لا توجد خانات متاحة لهذا المنتج", missingCustomer: "اختر عميلاً قبل تأكيد البيع",
    invalidDates: "تاريخ الانتهاء يجب أن يكون بعد تاريخ البداية", createCustomerError: "تعذر إنشاء العميل",
  },
  payments: { amount: "المبلغ", method: "الطريقة", paidAt: "تاريخ الدفع", notes: "ملاحظات" },
  phase3: {
    dashboard: "لوحة المتابعة", expiringSoon: "تنتهي قريباً", overdue: "اشتراكات متأخرة", freeSlots: "الخانات المتاحة", quickTotals: "ملخص العمل",
    withinOneDay: "خلال يوم", withinThreeDays: "خلال 3 أيام", withinSevenDays: "خلال 7 أيام", activeSubscriptions: "الاشتراكات النشطة", totalAccounts: "إجمالي الحسابات", monthlyRevenue: "إيرادات هذا الشهر",
    noOverdue: "لا توجد اشتراكات متأخرة", noExpiringSoon: "لا توجد اشتراكات تنتهي في هذه الفترة", daysRemaining: (days: number) => days < 0 ? `متأخر ${Math.abs(days)} يوم` : days === 0 ? "ينتهي اليوم" : `باقي ${days} يوم`,
    whatsappReminder: (name: string, product: string, date: string) => `مرحباً ${name}، نذكرك بأن اشتراك ${product} ينتهي بتاريخ ${date}. يرجى التواصل معنا للتجديد.`,
    openWhatsapp: "إرسال تذكير", renew: "تجديد", renewTitle: "تجديد الاشتراك", renewDescription: "سيتم إنشاء اشتراك جديد وتسجيل الدفعة كاملة.", durationDays: "مدة التجديد بالأيام",
    previousPrice: "سعر التجديد", renewSuccess: "تم تجديد الاشتراك بنجاح", renewError: "تعذر تجديد الاشتراك", settings: "الإعدادات", reminderLeadDays: "أيام التذكير قبل الانتهاء",
    reminderRecipient: "مستلم التذكير", recipientStaff: "الموظف", recipientCustomer: "العميل", recipientBoth: "الموظف والعميل", graceDays: "فترة السماح بالأيام", businessName: "اسم النشاط",
    currency: "العملة", settingsHint: "تطبق هذه القيم مباشرة على التنبيهات والتجديدات.", settingsSaved: "تم حفظ الإعدادات", users: "إدارة المستخدمين", addUser: "إضافة مستخدم",
    editUser: "تعديل المستخدم", resetPassword: "إعادة تعيين كلمة المرور", newPassword: "كلمة المرور الجديدة", name: "الاسم", email: "البريد الإلكتروني", role: "الصلاحية",
    roleAdmin: "مدير", roleStaff: "موظف", enabled: "مفعل", disabled: "معطل", userSaved: "تم حفظ المستخدم", passwordReset: "تم تحديث كلمة المرور", audit: "سجل التدقيق",
    who: "المستخدم", action: "الإجراء", entity: "العنصر", when: "الوقت", allActions: "كل الإجراءات", report: "تقرير الإيرادات", revenueByProduct: "الإيرادات حسب المنتج", refunded: "مسترجع",
    paymentsCount: "عدد الدفعات", adminOnly: "هذه الصفحة متاحة للمدير فقط", loading: "جارٍ التحميل...", save: "حفظ", close: "إغلاق", notes: "ملاحظات",
    noDataYet: "سيتم عرض المعلومات لاحقاً عندما تتوفر",
    revenueTrend: "اتجاه الإيرادات الشهرية",
    selectMonth: "اختر الشهر",
    averagePayment: "متوسط الدفعة",
    changeVsPrevMonth: "التغيير مقارنة بالشهر السابق",
    monthNames: ["يناير","فبراير","مارس","أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر","أكتوبر","نوفمبر","ديسمبر"] as const,
  },
  website: {
    nav: "الموقع الإلكتروني",
    title: "الموقع الإلكتروني",
    hint: "اضبط صفحة المتجر العامة التي يراها العملاء قبل التواصل عبر واتساب.",
    lockedTitle: "ميزة الموقع غير متاحة حالياً",
    lockedDescription: "تم إيقاف إمكانية استخدام الموقع لهذا النشاط من إدارة المنصة. تواصل مع مالك المنصة لإعادة التفعيل.",
    live: "الموقع مفعل",
    offline: "الموقع غير مفعل",
    slug: "رابط المتجر",
    slugHint: "أحرف إنجليزية صغيرة وأرقام وشرطات فقط",
    whatsapp: "رقم واتساب المتجر",
    whatsappHint: "اكتب الرقم بصيغة دولية مثل 96279XXXXXXX",
    name: "اسم المتجر",
    description: "وصف قصير",
    publicLink: "رابط المتجر",
    save: "حفظ إعدادات الموقع",
    saved: "تم حفظ إعدادات الموقع",
    saveError: "تعذر حفظ إعدادات الموقع",
    missingLiveInfo: "أدخل رابط المتجر ورقم واتساب صحيح قبل تفعيل الموقع",
    duplicateSlug: "رابط المتجر مستخدم من نشاط آخر",
    platformWebsites: "مواقع الأنشطة",
    platformHint: "تحكم بإتاحة ميزة الموقع الإلكتروني لكل نشاط.",
    accessAllowed: "مسموح",
    accessBlocked: "موقوف",
    updateAccessError: "تعذر تحديث إتاحة الموقع",
    productsSection: "إعدادات المنتجات",
    productsSectionHint: "خصّص اسم كل منتج ووصفه وصورته في صفحة المتجر.",
    productDisplayName: "الاسم في المتجر",
    productDescription: "الوصف",
    productImage: "الصورة",
    productImageHint: "JPG أو PNG أو WebP، حجم أقصى 2 ميغابايت",
    uploadImage: "رفع صورة",
    deleteImage: "حذف الصورة",
    saveProduct: "حفظ",
    productSaved: "تم حفظ إعدادات المنتج",
    productSaveError: "تعذر حفظ المنتج",
    productImageUploaded: "تم رفع الصورة",
    productImageUploadError: "تعذر رفع الصورة",
    productImageDeleted: "تم حذف الصورة",
    productImageDeleteError: "تعذر حذف الصورة",
    productImageTooLarge: "حجم الصورة يتجاوز 2 ميغابايت",
    logo: "شعار المتجر",
    logoHint: "JPG أو PNG أو WebP، حجم أقصى 2 ميغابايت",
    uploadLogo: "رفع شعار",
    deleteLogo: "حذف الشعار",
    logoUploaded: "تم رفع الشعار",
    logoUploadError: "تعذر رفع الشعار",
    logoDeleted: "تم حذف الشعار",
    logoDeleteError: "تعذر حذف الشعار",
  },
  store: {
    loading: "جاري تحميل المتجر...",
    notFound: "المتجر غير موجود",
    available: "متوفر",
    unavailable: "غير متوفر حالياً",
    orderNow: "اطلب الآن",
    askAvailability: "اسأل عن التوفر",
    durationDays: (days: number) => `${days} يوم`,
    orderMessage: (product: string, price: string, duration: number) => `مرحباً، أريد الاشتراك في ${product} بسعر ${price} لمدة ${duration} يوم.`,
    availabilityMessage: (product: string) => `مرحباً، أريد الاستفسار عن توفر ${product}.`,
  },
  dataSecurity: {
    nav: "امن البيانات",
    title: "امن البيانات",
    intro: "نزّل نسخة احتياطية مشفّرة من بيانات نشاطك التجاري كاملةً.",
    downloadButton: "تنزيل نسخة احتياطية",
    warning: "الملف محمي بكلمة مرور تختارها ويحتوي على كلمات مرور الحسابات. احتفظ به في مكان آمن — لا يمكن استرجاع كلمة المرور إذا فُقدت.",
    modalTitle: "تنزيل نسخة احتياطية مشفّرة",
    passphraseLabel: "كلمة مرور الملف",
    confirmLabel: "تأكيد كلمة المرور",
    tooShort: "كلمة المرور يجب أن تكون 8 أحرف على الأقل",
    mismatch: "كلمتا المرور غير متطابقتين",
    generating: "جارٍ التحضير…",
    success: "تم تنزيل النسخة الاحتياطية",
    error: "تعذّر إنشاء النسخة الاحتياطية، حاول مجددًا",
  },
};
